### ISSUE TITLE
setting thermostatFanMode generating error

### ISSUE THREAD

**Issue by neogeocabs** [daltskin/SmartThingsNet#10]
First off, thank you for creating SmartThingsNet! :1st_place_medal: 

I'm currently getting the following error:

> ApiException: Error calling ExecuteDeviceCommands: {"requestId":"1D32CFBC-50A1-442F-8200-1D6E2FFF42A5","error":{"code":"ConstraintViolationError","message":"The request is malformed.","details":[{"code":"NotValidValue","target":"[0].command","message":"circulate is not a valid value.","details":[]}]}}

when I tried to set thermostat fan mode, see code below:

> var command = new DeviceCommandsRequest(new List<DeviceCommand> { new DeviceCommand("main", "thermostatFanMode", input.FanMode, null) });
                var response = await api.ExecuteDeviceCommandsAsync(input.DeviceID, command);

as per reference: [https://smartthings.developer.samsung.com/docs/api-ref/capabilities.html?highlight=thermostatFanMode](url)  circulate is a valid value.

> thermostatFanMode
The current mode of the fan on a thermostat
*Type: *ENUM *Required: *Yes
Possible values:
auto - The fan is on auto
circulate - The fan is circulating
followschedule - The fan is set to follow predefined schedule
on - The fan is on

this was confirmed by getting supportedThermostatFanModes value which gave me this result {[  "auto",  "circulate",  "on"]}

**Comment by daltskin** [comment]
ok, since the SmartThings API is still in preview, please first check that the API behaves in the way you expect it to - best way is to hit it directly with something like Postman and check response.  The api call will look something like the following:

`POST: https://api.smartthings.com/v1/devices/:deviceId/commands`

If API works as expected, then I'll see if I can reproduce.

**Comment by neogeocabs** [comment]
I submitted a ticket to SmartThings and the issue is on their side.  It's the inconsistency on how they are implementing the API.  To set/change thermostatMode you can use the following code:

`new DeviceCommand("main", "thermostatMode", "auto", null)`

But to set thermostatFanMode you need to pass the new command as argument and command to setThermostatFanMode.  See below:

`new DeviceCommand("main", "thermostatFanMode", "setThermostatFanMode", new List<object> { "auto" })`

Something to think about when sending commands.  Not sure if you want to add a note in your documentation as this might apply to other device commands not just thermostatFanMode.  Hope this help others.

The issue is not on SmartThingsNet.  Thanks for the awesome work!

**Comment by daltskin** [comment]
Thanks for reporting back!
