### ISSUE TITLE
ListSubscriptions - Doesn't work with PAT, required OAUTH?

### ISSUE THREAD

**Issue by doug62** [daltskin/SmartThingsNet#13]
Greetings when I attempt to call: ListSubscriptions I get access forbidden - i think this doesn't work with PAT which differs from your doc - is this true?  How could I trade a PAT for OAUTH in this? Or do I need to hook the INIT/UPDATE events and store tokens?

Thanks

**Comment by daltskin** [comment]
First I would test that the underlying API works in the way you expect.  If you take a look at: https://developer-preview.smartthings.com/api/public/#operation/listSubscriptions then run a Postman with a valid token for a given installed appId.  For example with the following I still see 403s.

`9194c801-68de-497c-881f-5b3acbec392f` is "SmartThings Cooking"

https://api.smartthings.com/v1/installedapps/9194c801-68de-497c-881f-5b3acbec392f/subscriptions
