### ISSUE TITLE
Pagination approach in client? How?

### ISSUE THREAD

**Issue by KenKilty** [daltskin/SmartThingsNet#3]
Firstly this is awesome work and thank you for putting this together. Using the latest NuGet package I am curious how pagination works in the generated client. I see the mapped devicesResponse.Links.Next.Href and devicesResponse.Links.Prev.Href properties on the response but I don't see those accepted as inputs in the any of the method calls. So I am unsure how to paginate through the results. Is this perhaps an issue with the swagger def using '_links' vs 'links' perhaps?

Repro of the behavior just pulling battery status for the first device on hub.

```
async Task Main()
{
	Configuration config = new Configuration()
	{
		BasePath = "https://api.smartthings.com/v1",
		AccessToken = Environment.GetEnvironmentVariable("STDeviceToken")
	};
	
	DevicesApi devicesApiClient = new DevicesApi(config);
	PagedDevices devicesResponse = await devicesApiClient.GetDevicesAsync();
	
	// Pagination loop? devicesResponse.Links.Next or Prev

	foreach (Device device in devicesResponse.Items)
	{
		DeviceStatus status = await devicesApiClient.GetDeviceStatusAsync(device.DeviceId);

		status.Components["main"]["battery"].Dump();
		break; //just one for testing
	}
}
```

**Comment by daltskin** [comment]
TBH I'm not sure this implemented in the underlying API see:

https://smartthings.developer.samsung.com/docs/api-ref/st-api.html#tag/devices

I've only ever seen empty results returned:

```
{
    "_links": {}
}
```

**Comment by KenKilty** [comment]
Understood and I agree after playing with the underlying raw REST API on the ST side.
