### ISSUE TITLE
RestSharp version issue

### ISSUE THREAD

**Issue by neogeocabs** [daltskin/SmartThingsNet#8]
Trying to integrate SmartThings on my project using SmartThingsNet.  I'm using .Net five and SmartThingsNet is failing if using RestSharp version above 106.10.1.

I'm getting this error:
> MethodAccessException: Attempt by method 'SmartThingsNet.Client.ApiClient.Exec(RestSharp.RestRequest, SmartThingsNet.Client.IReadableConfiguration)' to access method 'RestSharp.RestClient.AddHandler(System.Func`1<RestSharp.Deserializers.IDeserializer>, System.String[])' failed.

I used Nuget Package Manager in Visual Studio 2019 Version 16.8.3

**Comment by daltskin** [comment]
Thanks for reporting this - I've rev'd the dependency versions tonight.  Should be ok now: https://github.com/daltskin/SmartThingsNet/releases/tag/0.5.0

**Comment by neogeocabs** [comment]
Issue resolved on the new version.  Thank you! :+1:
